# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333739ee3fe9e406ae3a3d17538e3745ebf7c8b9b4d352ad3b3a5e0ab65583120ec5c023631311fa642f03a3220ae776ca33ba7404563bf074ab341f6ef33378

test:
  secret_key_base: a4e80afc8ac2fae3cc9eb4299527571f2f4791891e97996a32090cceefd7d82bc36e9d9205e1e01d99a5f9f7c4dbe8c8a4fcc9e84d712d03ec7f61bbbab594e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
